### ISSUE TITLE
[jsk_interactive_marker] build fail  on generating java message

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_visualization#551]

**Comment by wkentaro** [comment]
https://gist.github.com/wkentaro/da442028a4e383947d4a

**Comment by wkentaro** [comment]
```
Traceback (most recent call last):
  File "/opt/ros/indigo/share/genjava/cmake/../../../lib/genjava/genjava_gradle_project.py", line 14, in <module>
    genjava.main(sys.argv)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genjava/genjava_main.py", line 82, in main
    gradle_project.create(args.package, args.output_dir)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genjava/gradle_project.py", line 152, in create
    raise IOError("could not find %s on the ros package path" % msg_pkg_name)
IOError: could not find jsk_interactive_marker on the ros package path
Traceback (most recent call last):
  File "/opt/ros/indigo/share/genjava/cmake/../../../lib/genjava/genjava_gradle_project.py", line 14, in <module>
    genjava.main(sys.argv)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genjava/genjava_main.py", line 82, in main
    gradle_project.create(args.package, args.output_dir)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genjava/gradle_project.py", line 152, in create
    raise IOError("could not find %s on the ros package path" % msg_pkg_name)
IOError: could not find jsk_interactive_marker on the ros package path
make[2]: *** [java/jsk_interactive_marker/build.gradle] Error 1
make[1]: *** [CMakeFiles/jsk_interactive_marker_generate_messages_java.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [java/jsk_interactive_marker/build.gradle] Error 1
make[1]: *** [CMakeFiles/jsk_interactive_marker_generate_messages_java_gradle.dir/all] Error 2
make: *** [all] Error 2
```
any idea how to fix this error?
