### ISSUE TITLE
jsk_rviz_plugins build failure

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_visualization#764]
http://build.ros.org/job/Mbin_uB64__jsk_rviz_plugins__ubuntu_bionic_amd64__binary/44/

```
08:27:46 ccache /usr/lib/ccache/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"jsk_rviz_plugins\" -Djsk_rviz_plugins_EXPORTS -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu/devel/include -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src -I/opt/ros/melodic/include -I/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/usr/include/eigen3 -I/usr/include/OGRE/Overlay -I/usr/include/OGRE -I/usr/include/pcl-1.8 -I/usr/include/vtk-6.3 -I/usr/include/freetype2 -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu -I/usr/include/hdf5/openmpi -I/usr/include/libxml2 -I/usr/include/jsoncpp -I/usr/include/tcl -I/usr/include/ni -I/usr/include/openni2 -I/usr/include/opencv -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -g -O2 -fdebug-prefix-map=/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -g -std=c++11 -fPIC -std=gnu++11 -o CMakeFiles/jsk_rviz_plugins.dir/src/ambient_sound_display_groovy.cpp.o -c /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/ambient_sound_display_groovy.cpp
08:28:09 [ 28%] Building CXX object CMakeFiles/jsk_rviz_plugins.dir/src/ambient_sound_visual.cpp.o
08:28:09 ccache /usr/lib/ccache/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"jsk_rviz_plugins\" -Djsk_rviz_plugins_EXPORTS -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu/devel/include -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src -I/opt/ros/melodic/include -I/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/usr/include/eigen3 -I/usr/include/OGRE/Overlay -I/usr/include/OGRE -I/usr/include/pcl-1.8 -I/usr/include/vtk-6.3 -I/usr/include/freetype2 -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu -I/usr/include/hdf5/openmpi -I/usr/include/libxml2 -I/usr/include/jsoncpp -I/usr/include/tcl -I/usr/include/ni -I/usr/include/openni2 -I/usr/include/opencv -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -g -O2 -fdebug-prefix-map=/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -g -std=c++11 -fPIC -std=gnu++11 -o CMakeFiles/jsk_rviz_plugins.dir/src/ambient_sound_visual.cpp.o -c /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/ambient_sound_visual.cpp
08:28:16 [ 29%] Building CXX object CMakeFiles/jsk_rviz_plugins.dir/src/footstep_display.cpp.o
08:28:16 ccache /usr/lib/ccache/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"jsk_rviz_plugins\" -Djsk_rviz_plugins_EXPORTS -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu/devel/include -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src -I/opt/ros/melodic/include -I/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/usr/include/eigen3 -I/usr/include/OGRE/Overlay -I/usr/include/OGRE -I/usr/include/pcl-1.8 -I/usr/include/vtk-6.3 -I/usr/include/freetype2 -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu -I/usr/include/hdf5/openmpi -I/usr/include/libxml2 -I/usr/include/jsoncpp -I/usr/include/tcl -I/usr/include/ni -I/usr/include/openni2 -I/usr/include/opencv -I/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -g -O2 -fdebug-prefix-map=/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -g -std=c++11 -fPIC -std=gnu++11 -o CMakeFiles/jsk_rviz_plugins.dir/src/footstep_display.cpp.o -c /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp
08:28:28 /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp: In destructor ‘virtual jsk_rviz_plugins::FootstepDisplay::~FootstepDisplay()’:
08:28:28 /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp:84:21: error: invalid use of incomplete type ‘class Ogre::SceneManager’
08:28:28        scene_manager_->destroySceneNode(node);
08:28:28                      ^~
08:28:28 In file included from /opt/ros/melodic/include/rviz/message_filter_display.h:37:0,
08:28:28                  from /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.h:41,
08:28:28                  from /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp:36:
08:28:28 /opt/ros/melodic/include/rviz/display_context.h:42:7: note: forward declaration of ‘class Ogre::SceneManager’
08:28:28  class SceneManager;
08:28:28        ^~~~~~~~~~~~
08:28:28 /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp: In member function ‘virtual void jsk_rviz_plugins::FootstepDisplay::onInitialize()’:
08:28:28 /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp:149:33: error: invalid use of incomplete type ‘class Ogre::SceneManager’
08:28:28      scene_node_ = scene_manager_->getRootSceneNode()->createChildSceneNode();
08:28:28                                  ^~
08:28:28 In file included from /opt/ros/melodic/include/rviz/message_filter_display.h:37:0,
08:28:28                  from /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.h:41,
08:28:28                  from /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp:36:
08:28:28 /opt/ros/melodic/include/rviz/display_context.h:42:7: note: forward declaration of ‘class Ogre::SceneManager’
08:28:28  class SceneManager;
08:28:28        ^~~~~~~~~~~~
08:28:28 /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp: In member function ‘virtual void jsk_rviz_plugins::FootstepDisplay::allocateTexts(size_t)’:
08:28:28 /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp:196:23: error: invalid use of incomplete type ‘class Ogre::SceneManager’
08:28:28          scene_manager_->destroySceneNode(node);
08:28:28                        ^~
08:28:28 In file included from /opt/ros/melodic/include/rviz/message_filter_display.h:37:0,
08:28:28                  from /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.h:41,
08:28:28                  from /tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/src/footstep_display.cpp:36:
08:28:28 /opt/ros/melodic/include/rviz/display_context.h:42:7: note: forward declaration of ‘class Ogre::SceneManager’
08:28:28  class SceneManager;
08:28:28        ^~~~~~~~~~~~
08:28:28 CMakeFiles/jsk_rviz_plugins.dir/build.make:273: recipe for target 'CMakeFiles/jsk_rviz_plugins.dir/src/footstep_display.cpp.o' failed
08:28:28 make[4]: *** [CMakeFiles/jsk_rviz_plugins.dir/src/footstep_display.cpp.o] Error 1
08:28:28 make[4]: Leaving directory '/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu'
08:28:28 CMakeFiles/Makefile2:2884: recipe for target 'CMakeFiles/jsk_rviz_plugins.dir/all' failed
08:28:28 make[3]: *** [CMakeFiles/jsk_rviz_plugins.dir/all] Error 2
08:28:28 make[3]: Leaving directory '/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu'
08:28:28 Makefile:132: recipe for target 'all' failed
08:28:28 make[2]: Leaving directory '/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5/obj-x86_64-linux-gnu'
08:28:28 make[2]: *** [all] Error 2
08:28:28 dh_auto_build: cd obj-x86_64-linux-gnu && make -j1 returned exit code 2
08:28:28 make[1]: *** [override_dh_auto_build] Error 2
08:28:28 debian/rules:35: recipe for target 'override_dh_auto_build' failed
08:28:28 make[1]: Leaving directory '/tmp/binarydeb/ros-melodic-jsk-rviz-plugins-2.1.5'
08:28:28 debian/rules:22: recipe for target 'build' failed
08:28:28 make: *** [build] Error 2
08:28:28 dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
08:28:28 E: Building failed
08:28:28 Traceback (most recent call last):
08:28:28   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 138, in build_binarydeb
08:28:28     subprocess.check_call(cmd, cwd=source_dir)
08:28:28   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
08:28:28     raise CalledProcessError(retcode, cmd)
08:28:28 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-melodic-jsk-rviz-plugins']' returned non-zero exit status 1.
08:28:28 # END SUBSECTION
```

**Comment by knorth55** [comment]
build fixed http://build.ros.org/job/Mbin_uB64__jsk_rviz_plugins__ubuntu_bionic_amd64__binary/61/
